# Generated by Django 5.2.17 on 2026-09-12 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="achievement_icons/"
                    ),
                ),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("TOTAL_QUESTS", "Total Quests"),
                            ("STREAK_DAYS", "Streak Days"),
                            ("LEVEL_REACHED", "Level Reached"),
                            ("GOLD_EARNED", "Gold Earned"),
                            ("SPECIFIC_CATEGORY", "Specific Category"),
                        ],
                        max_length=50,
                    ),
                ),
                ("requirement_value", models.IntegerField()),
                ("reward_xp", models.IntegerField(default=0)),
                ("reward_gold", models.IntegerField(default=0)),
                ("rarity", models.CharField(default="COMMON", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
