# Generated by Django 5.2.17 on 2026-09-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="rarity",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="requirement_type",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="requirement_value",
        ),
        migrations.AddField(
            model_name="achievement",
            name="criteria_type",
            field=models.CharField(
                choices=[
                    ("LEVEL", "Reach Level"),
                    ("QUESTS_COMPLETED", "Quests Completed"),
                    ("STREAK", "Habit Streak"),
                    ("BOSS_KILLS", "Boss Kills"),
                ],
                default="LEVEL",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="criteria_value",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="icon",
            field=models.CharField(default="🏆", max_length=50),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
