# Generated by Django 5.2.17 on 2026-09-12 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STUDY", "Study"),
                            ("CODING", "Coding"),
                            ("FITNESS", "Fitness"),
                            ("HEALTH", "Health"),
                            ("READING", "Reading"),
                            ("WORK", "Work"),
                            ("FINANCE", "Finance"),
                            ("SOCIAL", "Social"),
                            ("PERSONAL", "Personal"),
                            ("MEDITATION", "Meditation"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=50,
                    ),
                ),
                (
                    "attribute",
                    models.CharField(
                        choices=[
                            ("STRENGTH", "Strength"),
                            ("INTELLECT", "Intellect"),
                            ("AGILITY", "Agility"),
                            ("VITALITY", "Vitality"),
                            ("WISDOM", "Wisdom"),
                            ("DISCIPLINE", "Discipline"),
                            ("CHARISMA", "Charisma"),
                        ],
                        default="STRENGTH",
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                            ("EPIC", "Epic"),
                        ],
                        default="MEDIUM",
                        max_length=50,
                    ),
                ),
                ("estimated_minutes", models.IntegerField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("recurring", models.BooleanField(default=False)),
                (
                    "recurrence_rule",
                    models.CharField(
                        blank=True, help_text="e.g., daily, weekly", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="TODO",
                        max_length=50,
                    ),
                ),
                ("xp_reward", models.IntegerField(default=50)),
                ("gold_reward", models.IntegerField(default=25)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
