# Generated by Django 5.2.17 on 2026-09-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("friends", "Friends Only"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reduced_motion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[
                    ("dark", "Dark Theme"),
                    ("light", "Light Theme"),
                    ("system", "System Default"),
                ],
                default="dark",
                max_length=20,
            ),
        ),
    ]
