# Generated by Django 5.2.17 on 2026-09-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='item_type',
            field=models.CharField(choices=[('AVATAR', 'Avatar'), ('FRAME', 'Frame'), ('THEME', 'Theme'), ('TITLE', 'Title'), ('BADGE', 'Badge'), ('EFFECT', 'Effect'), ('WEAPON', 'Weapon'), ('ARMOR', 'Armor'), ('ACCESSORY', 'Accessory')], default='AVATAR', max_length=50),
        ),
    ]
