# Generated by Django 5.2.17 on 2026-09-12 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rpg_class",
                    models.CharField(
                        choices=[
                            ("WARRIOR", "Warrior"),
                            ("MAGE", "Mage"),
                            ("ROGUE", "Rogue"),
                            ("RANGER", "Ranger"),
                            ("MONK", "Monk"),
                            ("ENGINEER", "Engineer"),
                            ("NONE", "None"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                ("total_xp", models.BigIntegerField(default=0)),
                ("gold", models.IntegerField(default=100)),
                ("health", models.IntegerField(default=100)),
                ("energy", models.IntegerField(default=100)),
                ("strength", models.IntegerField(default=10)),
                ("intellect", models.IntegerField(default=10)),
                ("agility", models.IntegerField(default=10)),
                ("vitality", models.IntegerField(default=10)),
                ("wisdom", models.IntegerField(default=10)),
                ("discipline", models.IntegerField(default=10)),
                ("charisma", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
