# Generated by Django 5.2.17 on 2026-09-12 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("QUEST_COMPLETED", "Quest Completed"),
                            ("LEVEL_UP", "Level Up"),
                            ("ACHIEVEMENT_UNLOCKED", "Achievement Unlocked"),
                            ("ITEM_PURCHASED", "Item Purchased"),
                            ("STREAK_MILESTONE", "Streak Milestone"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=50,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
